package hermesacp

// Shared string constants extracted to satisfy goconst. Values mirror the
// Hermes native wire vocabulary, ACP field names, and internal state kinds.
const (
	valElicitation  = "elicitation"
	valBackpressure = "backpressure"
	valDeleted      = "deleted"
	valUnknown      = "unknown"
	valForm         = "form"
	valURL          = "url"
	valServer       = "server"
	valACPGoHermes  = "acp-go-hermes"
	valAssistant    = "assistant"
	valStop         = "stop"
	valText         = "text"
	valReasoning    = "reasoning"
	valAlways       = "always"
	valServe        = "serve"
	valAudio        = "audio"
	valUser         = "user"
	valStepFinish   = "step-finish"
	valTool         = "tool"
	valOnce         = "once"
	valReject       = "reject"
	valQuestion1    = "question_1"
	valString       = "string"
	valLength       = "length"
	valCancelled    = "cancelled"
	valPending      = "pending"
	valCompleted    = "completed"
	valRead         = "read"
	valEdit         = "edit"
	valDelete       = "delete"
	valHigh         = "high"
	valLow          = "low"
	valSecret       = "secret"
	valUnsupported  = "unsupported"
	valImage        = "image"
	valSuccess      = "success"
	valFile         = "file"

	defaultMimeType = "application/octet-stream"

	keyLimit    = "limit"
	keyMode     = "mode"
	keyType     = "type"
	keyTitle    = "title"
	keyMime     = "mime"
	keyFilename = "filename"

	evtApprovalRequest    = "approval.request"
	evtClarifyRequest     = "clarify.request"
	evtSecretRequest      = "secret.request"
	evtMessageDelta       = "message.delta"
	evtMessagePartUpdated = "message.part.updated"
	evtMessagePartCreated = "message.part.created"
	evtServerConnected    = "server.connected"
	evtSudoRequest        = "sudo.request"
	evtThinkingDelta      = "thinking.delta"
	evtTerminalReadReq    = "terminal.read.request"

	keySessionIDSnake = "session_id"
	keyValue          = "value"
	keyField          = "field"
	keySequence       = "sequence"
	keySource         = "source"
	keyEvent          = "event"
	keyQuestion       = "question"
	keyMessageID      = "messageId"

	msgHermesNeedsInput = "Hermes needs input"

	archiveEncodingTarZstdBase64 = "tar+zstd+base64"
	reasonTurn                   = "turn"
	reasonPermission             = "permission"
	reasonGeneration             = "generation"
	fileStateDB                  = "state.db"
	fileStateDBSHM               = "state.db-shm"
	fileStateDBWAL               = "state.db-wal"
	tableAccount                 = "account"
)
